services:
  - type: worker
    name: bilbasen-scraper
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /opt/render/project/.playwright
      PLAYWRIGHT_BROWSERS_PATH=/opt/render/project/.playwright playwright install chromium
    startCommand: |
      PLAYWRIGHT_BROWSERS_PATH=/opt/render/project/.playwright python main.py