services:
  - type: worker
    name: bilbasen-scraper
    env: python
    plan: free
    buildCommand: |  
      pip install -r requirements.txt
      playwright install --with-deps
    startCommand: python main.py
    envVars:
      - key: SUPABASE_URL
        value: https://mmhzdntjwkkpflglwchy.supabase.co
      - key: SUPABASE_API_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1taHpkbnRqd2trcGZsZ2x3Y2h5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NTMxNzA4NywiZXhwIjoyMDYwODkzMDg3fQ.KHCCOUENSAPJuxfJTdcT6a-zESt8HumumDzCz08zwHs
