services:
  - type: worker
    name: bilbasen-scraper
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      npx playwright install chromium --with-deps
    startCommand: python main.py