services:
  - type: worker
    name: bilbasen-scraper
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      PLAYWRIGHT_BROWSERS_PATH=./.playwright-cache playwright install chromium
    startCommand: |
      PLAYWRIGHT_BROWSERS_PATH=./.playwright-cache python main.py
