services:
  - type: background
    name: bilbasen-scraper
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SUPABASE_URL
        value: https://mmhzdntjwkkpflglwchy.supabase.co
      - key: SUPABASE_API_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1taHpkbnRqd2trcGZsZ2x3Y2h5Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0NTMxNzA4NywiZXhwIjoyMDYwODkzMDg3fQ.KHCCOUENSAPJuxfJTdcT6a-zESt8HumumDzCz08zwHs